#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

project=$1
origin="git@github.com:blueberryapps/haystack.git"
newOrigin="git@github.com:blueberryapps/$project"

git clone $origin $project

cd $project

git remote add parent $origin
git remote set-url origin $newOrigin
git push -u origin --all \
  && echo -e"\n\nProject $project initialized!" \
  || echo -e "\n\nProject $project initialized!\n\nPlease create repository called $project on https://github.com and then do manual push with 'git push -u origin --all'."
